### PR TITLE
Fix #124 (the second)

### LINKED ISSUE #124: Disable host / port match for single host applications
Is there any way to use aerys server without host name (by ip). 

```php
(new Aerys\Host)
    ->expose('0.0.0.0', 8089)
    // ... ->use
```
In this case aerys will assign "localhost" name by default but I need to access to it (API) without any host name just by some IP and port. When I'm trying to access it I get an error:
```html
<html>
<body>
<h1>400 Bad Request</h1>

<hr/>
<em>Thu, 12 Jan 2017 17:17:02 GMT</em>
<br/><br/>
</body>
</html>
```

My server logs looks like this:
```
2017-01-12T17:11:19.508998817Z [2017-01-12 17:11:19] debug accept 172.17.0.1:53013
2017-01-12T17:11:19.509241443Z [2017-01-12 17:11:19] debug GET /status HTTP/1.1 @ 172.17.0.1:53013
2017-01-12T17:11:19.509781032Z [2017-01-12 17:11:19] debug close 172.17.0.1:53013
```
Any hint?

### PR DESCRIPTION
**Pull request by bwoebi**
An alternate solution for #124 (previous PR at #170):

You can now set a specific expected port the client must specify in the Host header or wildcard port ("*") to avoid any port matching there.

### CODE REVIEW

File: test/VhostTest.php [hunk 1]
```diff
@@ -64,28 +101,28 @@ public function testCryptoVhost() {
...
      */
     public function testBadInterface() {
-        new Vhost("", [["rd.lo.wr.ey", 1025]], function () {}, []);
+        new Vhost("*", [["rd.lo.wr.ey", 1025]], function () {}, []);
     }
 
     /**
      * @expectedException \LogicException
-     * @expectedExceptionMessage Cannot have two hosts with the same `localhost:80` name
+     * @expectedExceptionMessage Cannot have two hosts with the same `localhost` name on the `127.0.0.1:80` interface
```
Comment (kelunik) [inline test/VhostTest.php]: It's still weird, should be `same name (...) on the same interface (...)` IMO.
